# Configuration for Dependabot.
# See https://docs.github.com/code-security/dependabot for details.
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10